---
# This starts a redis container

- name: (re)start redis
  docker:
    name: redis
    image: redis
    state: reloaded
    restart_policy: "{{ docker.restart.policy }}"
    ports:
      - "{{ redis.port }}:6379"

- name: wait until redis is up and running
  action: shell echo PING | nc -w 3 {{ inventory_hostname }} {{ redis.port }}
  register: result
  until: (result.rc == 0) and (result.stdout == '+PONG')
  retries: 12
  delay: 5