---
# This role will install Controller in group 'controllers' in the environment inventory

- name: pull the lastest image of controller
  shell: "docker pull {{ docker_registry }}whisk/controller:{{ docker_image_tag }}"
  when: docker_registry != ""

- name: (re)start controller
  docker:
    name: controller
    image: "{{ docker_registry }}whisk/controller:{{ docker_image_tag }}"
    state: reloaded
    restart_policy: "{{ docker.restart.policy }}"
    log_driver: syslog
    env:
      "COMPONENT_NAME": "controller"
      "CONSULSERVER_HOST": "{{ groups['consul_servers']|first }}"
      "CONSUL_HOST_PORT4": "{{ consul.port.http }}"
      "PORT": 8080
      "WHISK_VERSION_NAME": "{{ whisk.version.name }}"
      "WHISK_VERSION_DATE": "{{ whisk.version.date }}"
    volumes:
      - "{{ whisk_logs_dir }}/controller:/logs"
    ports:
      - "{{ controller.port }}:8080"

- name: wait until the Controller in this host is up and running
  wait_for:
    delay: 2
    host: "{{ inventory_hostname }}"
    port: "{{ controller.port }}"
    timeout: 60