# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.8

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false
  slack:
    on_pull_requests: false
    secure: "Rrj5ya7JV7bfgW3GXZpuRsX2e9/qsTpLLVZAzgq2Z3xW/IVAqeAM8DDR0tjPbR7Nou0RpPtE/ynkps4Qd6CGTBiCULpcGi2cXJ+p35WvaweWlFIKU0Vam9iEWXQ+bG1LwB61LrSmD7DJvOxkZiwtagqUfYLhVeD1WfgcWc/lj0F0julCScujqqJbj/jUnlkSm6VJz9m11NQkvZZ+YFgNYCPAQRmSh59K0ELximJ54C4/af05YHq6QLWUh/2Eoa68p3XzQyONtteMRvbAJgmMGIijQsKa+ZELrZPjz/5EplMA+FEUjoW6tn3NQjQgZOdDHq3fEbnuit0OOBMRu5QhYT0MjV6QJANYmJU2QqVoDubgTtQSeHJNYoM1fI15yfuSCJg+H6FnI0ncXRB3zz7EZ3zksKKeWZ20NQVKBNCYRNIBC8Im3ff8TbZdulH/Qk/NEeOJwpgm8yfUqUqLu3dt13KT0JdxEcQeOX5lRmz+XBrN6C52/fX0NstO2OCxpKhKcq2+B/Y3mCn6ywqAiTtaLyhPrW08cCB3sBX8y5/Q3do8KPWO1MiBc/K+qtK481bnkh41DaLasqpltpEkFhCW/Udl8iuYEkMWZwNdhEUv6uuPiKF9da4FJkhIV3xVYOzrjF6xR2BtmHVGnCVMMoCUQo9tG8K9tOf+omH+KezZPuw="
  webhooks:
    urls:
      secure: "Eqlsb7IQhyisDb4TJtQJUvlIu/2aW65qIR9q8wvwQlO/U0tceQ7darsK1NDZFoO6Xt+qGvG9P6z09m+TEDCIDqNrVcHZqXxaAPoYaTAmy5kEK5pMMN3bJ4/fnZIGHJsWWB0lCyG+qkQuU76rmjJX8Nq7pkk3jMit8PodkY0ZgIHQ3yJ+eHotN0KplW8U0hmGjaph17wJ3tCmfTsjqkk0TTAjqJSCTsyvfeT36jhyXwzLz604H16Q7ESRqzKgneO7cpSurms1YzT0gjfX5FFCeDiy53FmyNu+rlnsHziwP3YP/hsu4C284lPBY0A8hfu2TAR8P+/AfZAcBgRy0fL0qqHNFR9Ko0dXXIb+oMIDEbIztSpVXOl1cUq/hYWxStPd8BNbdFBlwROY4lvXk5j1f1Q4mx7oH20E6+ex4HHvmMz7evFYkXQHzqqTVKx4/Luablg2tJWFCOyL5qzyJqAX3VjIulvVdGXvpt3fODXPaRw3BRYgmJddl67ER2Ep+428LviggoS6zVSAUONt/a5WCalXOBiuexmZEXjs2okDWhKYHZHhdr3nVjUpDAi7W+gqNHObAgeRrD5KKM6AdI8wcNCzx3ZJ2bxJOUdUfx/P+To0mKAxcVFSUhbmVLFStSXGQTGHtCpm0GKKgw7hYqn2BGAr27nzKsQyxPROmM3GkN0="

install: true

before_install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh
  - ./tools/travis/box-upload.py "/home/travis/build/openwhisk/openwhisk/logs" "$TRAVIS_BUILD_ID-$TRAVIS_BRANCH.tar.gz"
