# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.8

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false
  slack:
    rooms:
      - secure: "Rrj5ya7JV7bfgW3GXZpuRsX2e9/qsTpLLVZAzgq2Z3xW/IVAqeAM8DDR0tjPbR7Nou0RpPtE/ynkps4Qd6CGTBiCULpcGi2cXJ+p35WvaweWlFIKU0Vam9iEWXQ+bG1LwB61LrSmD7DJvOxkZiwtagqUfYLhVeD1WfgcWc/lj0F0julCScujqqJbj/jUnlkSm6VJz9m11NQkvZZ+YFgNYCPAQRmSh59K0ELximJ54C4/af05YHq6QLWUh/2Eoa68p3XzQyONtteMRvbAJgmMGIijQsKa+ZELrZPjz/5EplMA+FEUjoW6tn3NQjQgZOdDHq3fEbnuit0OOBMRu5QhYT0MjV6QJANYmJU2QqVoDubgTtQSeHJNYoM1fI15yfuSCJg+H6FnI0ncXRB3zz7EZ3zksKKeWZ20NQVKBNCYRNIBC8Im3ff8TbZdulH/Qk/NEeOJwpgm8yfUqUqLu3dt13KT0JdxEcQeOX5lRmz+XBrN6C52/fX0NstO2OCxpKhKcq2+B/Y3mCn6ywqAiTtaLyhPrW08cCB3sBX8y5/Q3do8KPWO1MiBc/K+qtK481bnkh41DaLasqpltpEkFhCW/Udl8iuYEkMWZwNdhEUv6uuPiKF9da4FJkhIV3xVYOzrjF6xR2BtmHVGnCVMMoCUQo9tG8K9tOf+omH+KezZPuw="
      - secure: "WgdL9/Z/9+rl6edh+mqDiO0mx8JpxYwIrudYwuZUZ7d/9oUzS8Miid7au7Y1PP0CVPVDEvastw6+NnIVA/BIHTBNj488dTeNXumaaNQlaTTvaI9OLN1w3+GVVFuF64gmJ6I2T6x+qxqlYOwQhyZ8jZEJUXQ3VwE6DPz+KNqpBy+6GgWEvi+2lgGhc2Ko3SPAtcDWAdE6t8ELaO2uLh/JU60ndAi4yT297fOfwWi4I1aee5a+LajbJN6Mz89o5o0Y2GHV83a3D/ablt1CH3kRSErqLV3HDbt5eRR4yFhTPpbZG8yeWcZkP0oKyt3QqSen1paiEeqr7R9OspDf2OLSlWx7TGm/BnNW/3YRI3+gUPHqaJPCLldNRWnbYYd0RFGjVOfVOoYhAWAMdkWT48jX3YGE1LaZ0SwlxpMy5Fpj8Q22SVXY51o5Pw1UomUhGz2Hjfj8b0WbkWQ+q5qpgR8/z4Zfz5i3MY03mQNzeXs4Z9NoznIiz+9eQVpi4tkjUH3o2AFi6VXTdire61vfhFG3iYYqo2woKwNWOVaK/g0l13EVWiK62YxQEUZJbmhLb6VQrABrB2FCWl/+zZOOR3OUeie3AgAmxEwjxN9Y1IgMy0bJWEZ+ECf//39XMgj5Ys/gPsejDjPsWxhO6cuNtGq9K6RsPij1a0E+01JcyrNyNX0="
    on_pull_requests: false
    on_success: change
    on_failure: always
  webhooks:
    urls:
      secure: "e0nxBQzlLu0QdROB01ZngnYA7uf7x+kdQIzPDzruTRyKKvZRf1lgRfasE/XIcUes9zHQOuOwZZL9XDnFvEYAMWtCIYk/639D7UzgOz6UlpKo3l9VEP3HG7k2bQ+UPXpmMmoR7YL1ewxBE54uQEOztI4IlW94LHEGkm/OkvDuu0+VAqG9XVMlEt1sHd0u61qqBNAuQ8Lres68yTi1E+y5MbDgKyTZAmbRVbQ0uI9tCu9xJtSRZSXRs9DN641bTLJzumGfIpFTx9v0QBeqvVNNLH/f4/AIX6pq4aXIPsnu7LgMX/7qjrxpj9P8oc+FDGHfZhH2/XzCyj9qhEwu5RhSXt/lFkOkjNiQ+fAJ7OaNMfIVADreDnS0C4csdxr+M6gWqi0HMjjaHubZZLD/IZgIaoOyPXceOYqo1AjWLMdMW4YqfJ4H5jti2hgG8vXTu+V8ZJpmHzdyEBF2sLla12EipGofN/BzqazcoWKNZWKWbU7smZwMWAIJnXOWw1MpQjjUPZY+qufB04/zpHlTE1F2RETcFnm9wuUWV1AUo6SWxOJ4LurHcu05jT1FAvwDWnacjgzht3NiZA9z/wwpRoppDYLOkTYm3keEoS4xk8aJU9YjBvBhxT4qSAqn3RbCHQtEjxQseJvo45Bgy7DV2xAi3o+tY74+pXPE5//ARVRnsWE="


install: true

before_install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh
  - ./tools/travis/box-upload.py "/home/travis/build/openwhisk/openwhisk/logs" "$TRAVIS_BUILD_ID-$TRAVIS_BRANCH.tar.gz"
