version: '3'

networks:
  default:
    external:
      # Match the network name used by devtool docker compose setup
      name: openwhisk_default

services:
  user-events:
    image: bladerunner/user-metrics
    ports:
      - "9095:9095"
    environment:
      - KAFKA_HOSTS=kafka:9092

  prometheus:
    image: prom/prometheus:v2.5.0
    volumes:
      - ./compose/prometheus/:/etc/prometheus/
      - ~/tmp/openwhisk/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9096:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ~/tmp/openwhisk/grafana:/var/lib/grafana
      - ./compose/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false