---
# This role will deploy a database server. Use the role if you want to use CouchCB locally instead of Cloudant. 
# In initdb mode it will start the CouchDB container.
# In clean mode it will remove the CouchDB container.

- include: initdb.yml
  when: mode == "initdb" and db_provider == "CouchDB"

- include: clean.yml
  when: mode == "clean" and db_provider == "CouchDB"
