---
# Install the appropriate CLI into the ansible host for the routemgmt tasks

# TODO - This step may need to be a separate role/task to account for
#        docker-machine based installations.
- name: "Grab the local CLI from the binaries unarchived into nginx"
  copy:
    src: "{{ openwhisk_cli.nginxdir.name }}/{{ os }}/{{ arch }}/{{ wsk }}"
    dest: "{{ openwhisk_home }}/bin"
  vars:
    arch: "{{ ansible_machine | replace ('x86_64', 'amd64') }}"
    os: "{{ ansible_system | lower | replace('darwin', 'mac') }}"
    wsk: "{{ ( ansible_system == 'Windows') | ternary('wsk.exe', 'wsk') }}"
