---
# Tasks for handling CLI customization and publishing

- name: "ensure nginx directory for cli exists"
  file:
    path: "{{ cli_nginx_dir }}"
    state: directory

- name: "download and unarchive wsk cli for mac"
  include: >
    download_cli_mac.yml
  when: "'environments/mac' in inventory_dir"

- name: "download and unarchive wsk cli for linux"
  include: >
    download_cli_linux.yml
  when: "'environments/mac' not in inventory_dir"
