---
# Tasks for handling CLI customization and publishing

- name: "ensure nginx directory for cli exists"
  file:
    path: "{{ cli_nginx_dir }}"
    state: directory

- name: "ensure openwhisk cli directory for binaries exists"
  file:
    path: "{{ openwhisk_cli.location }}/bin"
    state: directory

- set_fact:
    cli_installation_mode="{{ openwhisk_cli.installation_mode }}"

- name: "download the binaries from the release page of OpenWhisk CLI"
  include: download_openwhisk_cli.yml
  with_items: "{{ cli_os }}"
  when: cli_installation_mode == "download"

- name: "download the source code if necessary and build the binaries locally"
  shell: "pwd"
  when: cli_installation_mode == "build"

- name: "copy all the cli binaries into nginx"
  copy: src={{ item }} dest={{ cli_nginx_dir }} owner=root mode=600
  with_fileglob:
    - "{{ openwhisk_cli.location }}/bin/*"

- include: download_cli.yml