---
# This role will initialize a cloudant db for Openwhisk. 
# In initdb mode it will create initial auth dbs in the database (you need to do this only once per environment).
# In deploy mode it does nothing atm.
# In clean mode it removes db template files.

- include: initdb.yml
  when: mode == "initdb"

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"
