---
# Remove API Gateway route management actions.

- name: remove route management actions
  shell: ./uninstallRouteMgmt.sh {{ catalog_auth_key }} {{ groups['edge'] | first }} {{ catalog_namespace }} {{ cli.path }} {{ apigw_auth_user }} chdir="{{ routemgmt.location }}/routemgmt"
  environment:
    OPENWHISK_HOME: "{{ openwhisk_home }}"
