# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# Remove etcd containers.

- name: remove etcd
  docker_container:
    name: etcd{{ groups['etcd'].index(inventory_hostname) }}
    keep_volumes: True
    state: absent
  ignore_errors: True
