---
# Generate a new self-signed certificate for the registry. To be used later.

- name: generate new cert
  shell: "openssl req -nodes -x509 -newkey rsa:2048 -keyout /tmp/whisk_docker_registry.key -out /tmp/whisk_docker_registry.crt -days 356 -subj '/C=DE/ST=BW/L={{location | default('Los Angeles')}}/O=WHISK/CN={{ groups['registry']|first }}'"
  when: "'prod' in deployment"

- name: generate new cert
  shell: "openssl req -nodes -x509 -newkey rsa:2048 -keyout files/whisk_docker_registry.key -out files/whisk_docker_registry.crt -days 356 -subj '/C=DE/ST=BW/L={{location | default('Los Angeles')}}/O=WHISK/CN={{ groups['registry']|first }}'"
  when: "'open' in deployment"
