---
# This role will install Kafka with Zookeeper in group 'kafka' in the environment inventory

- name: (re)start zookeeper
  docker_container:
    name: zookeeper
    image: zookeeper:3.4
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    ports:
      - "{{ zookeeper.port }}:2181"

- name: wait until the Zookeeper in this host is up and running
  action: shell echo ruok | nc -w 3 {{ inventory_hostname }} {{ zookeeper.port }}
  register: result
  until: (result.rc == 0) and (result.stdout == 'imok')
  retries: 36
  delay: 5

- name: "pull the {{ docker_image_tag }} image of kafka"
  shell: "docker pull {{ docker_registry }}{{ docker_image_prefix }}/kafka:{{ docker_image_tag }}"
  when: docker_registry != ""

- name: (re)start kafka
  docker_container:
    name: kafka
    image: "{{ docker_registry }}{{ docker_image_prefix }}/kafka:{{ docker_image_tag }}"
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    links:
      - "zookeeper:zookeeper"
    env:
      "EXPOSED_HOST": "{{ inventory_hostname }}"
    ports:
      - "{{ kafka.port }}:9092"

- name: wait until the kafka server started up
  shell: docker logs kafka
  register: result
  until: ('[Kafka Server 0], started' in result.stdout)
  retries: 10
  delay: 2

- name: create the active-ack topic
  shell: "docker exec kafka kafka-topics.sh --create --topic {{ item }} --replication-factor 1 --partitions 1 --zookeeper {{ inventory_hostname }}:{{ zookeeper.port }}"
  with_items:
    - completed

- name: create the invoker topics
  shell: "docker exec kafka kafka-topics.sh --create --topic invoke{{ item.0 }} --replication-factor 1 --partitions 1 --zookeeper {{ inventory_hostname }}:{{ zookeeper.port }}"
  with_indexed_items: "{{ groups['invokers'] }}"