---
# This role will install activator in group 'activators' in the environment inventory
# In deploy mode it will deploy activators.
# In clean mode it will remove the activator containers.

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"