---
# This task will write whisk.properties to the openwhisk_home. 
# Currently whisk.properties is still needed for consul and tests.

- name: write whisk.properties template to openwhisk_home
  template:
    src: whisk.properties.j2
    dest: "{{ openwhisk_home }}/whisk.properties"

- name: write whisk.env environment file for docker
  shell: cat {{ openwhisk_home }}/whisk.properties | awk -F= '!/^($|#)/{ gsub(/\./,"_", $1); print toupper($1)  "=" $2}' > {{ openwhisk_home }}/whisk.env
