---
# This playbook installs additional packages after whisk has been deployed.

- include: properties.yml

- hosts: ansible
  tasks:
    - include: tasks/installCatalog.yml
      when: (mode == "deploy" and catalog_source == "openwhisk")

- hosts: ansible
  tasks:
    - include: tasks/installOpenwhiskCatalog.yml
      when: (mode == "deploy" and catalog_source == "openwhisk-catalog")
