---
# This playbook installs additional packages after whisk has been deployed.

- include: properties.yml

- include: routemgmt.yml

- hosts: ansible
  tasks:
    - include: tasks/installOpenwhiskCatalog.yml
      when: (mode == "deploy")
      with_dict: "{{ catalog_repos }}"