---
# This playbook prepares ansible configuration

- hosts: localhost
  tasks:
  - name: find the ip of docker-machine
    local_action: shell "docker-machine" "ip" "{{docker_machine_name | default('whisk')}}"
    register: result
    ignore_errors: true

  - set_fact: 
      docker_machine_ip: "{{ result.stdout }}"
  
  - name: gen hosts for docker-machine 
    local_action: template src="{{playbook_dir}}/environments/mac/hosts.j2.ini" dest="{{ playbook_dir }}/environments/mac/hosts"
    when: result.rc == 0

  - name: prepare db_local.ini
    local_action: template src="db_local.ini.j2" dest="{{ playbook_dir }}/db_local.ini"
