---
# This playbook deploys an Openwhisk stack.  

- hosts: db
  roles:
  - db

- hosts: ansible
  roles:
  - prereq

- hosts: all:!ansible
  roles:
  - consul

- hosts: kafka
  roles:
  - kafka

- hosts: controllers
  roles:
  - controller

- hosts: activators
  roles:
  - activator

- hosts: invokers
  roles:
  - invoker

- hosts: edge
  roles:
  - nginx
  - cli

- hosts: ansible
  roles:
  - postdeploy