
# Remove the cloudant trigger service and logs directory.

- name: remove cloudant trigger
  docker_container:
    name: catalog_cloudant
    state: absent
  ignore_errors: true

- name: remove cloudant trigger logs directory
  file:
    path: "{{ whisk_logs_dir }}/cloudant-trigger"
    state: absent
  become: true
  