
# deploy mode will deploy the cloudant trigger service.
# clean mode will remove the cloudant service container and logs directory.

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"
