# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: OpenWhisk

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        env:
          ANSIBLE_CMD: "ansible-playbook -i environments/local -e docker_image_prefix=testing"
          GRADLE_PROJS_SKIP: ""
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: NgrokDebug
        run: |-
             if test -e .github/debug 
             then bash tools/github/debugAction.sh 
             fi
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_PASSWORD: ${{ secrets.NGROK_PASSWORD }}
      - name: WaitForNgrokDebug
        run: |-
             if test -e .github/debug 
             then bash tools/github/waitIfDebug.sh
             fi
   
