# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: distDocker

      - name: Set the image repo name and tag
        id: image_vars
        run: |
          # Construct an image id and includes the repo.
          IMAGE_ID=ghcr.io/${{ github.repository }}
          VERSION=latest

          # Set variables that can be used in other steps.
          echo ::set-output name=repo::$(echo $IMAGE_ID | awk '{print tolower($0)}')
          echo ::set-output name=tag::$(echo $VERSION | awk '{print tolower($0)}')

      - name: Login to github docker Registry
        run: docker login ghcr.io -u dylanturn -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ${{steps.image_vars.outputs.repo}}/controller:${{steps.image_vars.outputs.tag}}

      - name: Push the Docker image
        run: docker push ${{steps.image_vars.outputs.repo}}/invoker:${{steps.image_vars.outputs.tag}}

      - name: Push the Docker image
        run: docker push ${{steps.image_vars.outputs.repo}}/scheduler:${{steps.image_vars.outputs.tag}}